obj-$(CONFIG_COMMON_FP)	+= common_X00T/
obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X00T/
# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 start
obj-$(CONFIG_GOODIX_FP)	+= goodix_X00T/
# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 end
